### PR TITLE
Handle character accents combinations on Mac 

### LINKED ISSUE #88: Bugs with accents on Mac and PC
It seems I'm really taking the editor for a road test with my use cases! Anyway there are some issues I've experienced:

**On a PC**

Generally works well - `ALTGR + e` = é, `ALTGR + o` = ó, works as expected, however `ALTGR + a` selects all text rather than producing the expected á.

**On a Mac**

It seems that accents are generally broken in the editor on a mac. The reason appears to be the way you produce characters on a mac, using any kind of mac keyboard (UK or European).

> FYI: I'm going to refer to the mac 'alt' key as option here, for your reference

To produce accents, there is an 'accents key' - on international keyboards this is a single key, on UK/US keyboards, you press `option + e`.  After pressing the accents key (which shows up as ´, often highlighted) you press the key corresponding to the vowel you want.  For example: á.  

Try this in any standard editor and you see how it works.  Example:

Standard editor: `option + e, a` produces á
Carbon editor: `option + e, a` produces ´a

**Solution**

The PC solution should be fairly trivial - unassigning or being more specific for select all (which on a PC should be `CTRL + a` rather than `ALT + a` or `ALTGR + a`).

For Mac, I think the fix should also be fairly easy - it just involves some extra keyboard detection.  See: http://stackoverflow.com/questions/25332625/detect-accented-chars-typed-on-mac

Again I will give you a hand when I get time. Thanks.

### PR DESCRIPTION
**Pull request by mkhatib**
and fix Alt+A shortcut on windows.

Fixes #88 

cc/ @assembledadam

### CODE REVIEW

File: dist/carbon.js [hunk 1]
```diff
@@ -9460,12 +9632,50 @@ Utils.isRedo = function(event) {
  * @return {boolean} True if it is select all.
  */
 Utils.isSelectAll = function(event) {
-  return !!((event.ctrlKey || event.metaKey) &&
+  return !!((event.ctrlKey || (Utils.isMac() && event.metaKey)) &&
```
Comment (mkhatib) [inline dist/carbon.js:9635]: @assembledadam for the `alt+a` you're seeing on Windows, this is the only thing I can think would introduce this is maybe it is counting the alt key as meta. So I am protecting this with another check for the mac. Let me know if this fixes that issue, if it doesn't I'll have to download a VM to figure out what's happening.

**Comment by assembledadam** [comment]
Apologies, still not got round to testing this. It's on my list to address ASAP - still a few things to get to but I will report back!
